# В каком порядке применять условия, и надо ли их вообще применять
# Для отладки и ускорения программы
order = [6, 1, 2, 3, 4, 5]
# Надо ли печатать пример решения
print_solutions = true
# Ширина таблицы результатов
result_table_width = 4
# Параметры условий 1-го типа
first = [
    [0, 2, 4],
    [4, 1, 0],
    [8, 0, 8],
    [5, 3, 2],
    [2, 0, 6],
    [3, 3, 3],
    [6, 3, 4],

    # Дополнительные условия
    [7, 0, 7],

    # Пример решения, для отладки
    # [0,0,0],[0,1,1],[0,2,4],[0,3,0],
    # [1,0,1],[1,1,2],[1,2,0],[1,3,5],
    # [2,0,6],[2,1,4],[2,2,1],[2,3,6],
    # [3,0,3],[3,1,3],[3,2,3],[3,3,3],
    # [4,0,5],[4,1,0],[4,2,6],[4,3,1],
    # [5,0,4],[5,1,5],[5,2,5],[5,3,2],
    # [6,0,2],[6,1,6],[6,2,2],[6,3,4],
    # [7,0,7],[7,1,7],[7,2,7],[7,3,7],
    # [8,0,8],[8,1,8],[8,2,8],[8,3,8],
]

# Параметры условий 2-го типа
second = [
    [0, 5, 2, 6],
    [2, 7, 3, 7],
    [1, 8, 3, 8],
    [1, 6, 0, 2],
    [0, 0, 2, 4],

    # Дополнительные условия
    [1, 4, 2, 1],
    [1, 7, 3, 7],
    [0, 3, 2, 3],
]

# Параметры условий 3-го типа
third = [
    [1, 3,  "left", 1, 2],
    [1, 4, "right", 2, 5],
    [0, 2,  "left", 3, 1],
    [1, 5, "right", 2, 8],
    [3, 5, "right", 0, 5],

    # Дополнительные условия
    [1, 3,  "left", 0, 1],
]

# Параметры условий 4-го типа
forth = [
    [1, 0, 1, 7],
    [2, 7, 0, 4],
    [0, 0, 3, 3],
    [1, 3, 2, 0], #

    # Дополнительные условия
    [0, 4, 0, 8],
    [3, 1, 2, 7],
]
